[package]
name = "ann"
version = "0.1.0"
edition = "2021"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.75"
csv = "1.3.0"
nalgebra = "0.32.3"
rand = "0.8.5"
rand_distr = "0.4.3"
